SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [clients].[keyType](
	[id] [tinyint] IDENTITY(0,1) NOT NULL,
	[createDate] [datetime] NULL CONSTRAINT [DF_ClientsKeyType_CreateDate]  DEFAULT (getdate()),
	[name] [sysname] COLLATE Cyrillic_General_CI_AS NOT NULL,
 CONSTRAINT [PK_ClientsKeyType] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNIQ_ClientsKeyType_Name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [clients].[key](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[private] [varbinary](639) NOT NULL,
	[public] [varbinary](164) NOT NULL,
	[createDate] [datetime] NOT NULL CONSTRAINT [DF_clientsKey_GetDate]  DEFAULT (getdate()),
	[typeID] [tinyint] NOT NULL CONSTRAINT [DF_clientsKey_TypeID]  DEFAULT ((1)),
 CONSTRAINT [PK_clientsKey] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNIQ_clientsKey_Private] UNIQUE NONCLUSTERED 
(
	[private] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNIQ_clientsKey_Public] UNIQUE NONCLUSTERED 
(
	[public] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [clients].[key]  WITH CHECK ADD  CONSTRAINT [FK_clientsKey_TypeID] FOREIGN KEY([typeID])
REFERENCES [clients].[keyType] ([id])
GO
ALTER TABLE [clients].[key] CHECK CONSTRAINT [FK_clientsKey_TypeID]
GO
