SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [log].[activationService](
	[id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[paramList] [xml] NOT NULL,
	[createDate] [datetime] NOT NULL CONSTRAINT [DF_logActivationService_createDate]  DEFAULT (getdate()),
 CONSTRAINT [PK_logActivationService] PRIMARY KEY CLUSTERED 
(
	[id] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
