SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[FullBackup]
 @FileName nvarchar(256)
AS
BEGIN

SET NOCOUNT ON;

    BACKUP DATABASE [468602_userguide] TO DISK = @FileName WITH COPY_ONLY, NOFORMAT, NOINIT, NAME = N'sodapdf userguide Full Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10

END

GO
