CREATE TABLE [clients].[system]
(
[id] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[UID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_clientsSystem_UID] DEFAULT (newid()),
[machineKey] [uniqueidentifier] NOT NULL,
[motherboardKey] [varchar] (128) COLLATE Cyrillic_General_CI_AS NULL,
[physicalMAC] [varchar] (128) COLLATE Cyrillic_General_CI_AS NULL,
[clientID] [int] NULL,
[createDate] [datetime] NOT NULL CONSTRAINT [DF_licensesActivation_createDate] DEFAULT (getdate()),
[isAutogeneratedMachineKey] [bit] NOT NULL CONSTRAINT [DF__system__isAutoge__76619304] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [clients].[system] ADD CONSTRAINT [PK_clientsSystem] PRIMARY KEY CLUSTERED  ([id] DESC) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_clientsSystem_clientID] ON [clients].[system] ([clientID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [clientsSystem_machineKey] ON [clients].[system] ([machineKey]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UNIQ_clientsSystem_systemKeys] ON [clients].[system] ([physicalMAC], [machineKey], [motherboardKey]) ON [PRIMARY]
GO
ALTER TABLE [clients].[system] ADD CONSTRAINT [FK_clientsSystem_clientID] FOREIGN KEY ([clientID]) REFERENCES [clients].[client] ([id])
GO
