SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Create: 20120917 Tatiana Didenko
-- Modify: 20130313 Mykhaylo Tytarenko. Physical MAC can passed as empty string, not null (as another params). Change the logic of routine.
-- Description:	get systemID by physicalMAC, machineKey and motherboardKey
-- =============================================
CREATE function [clients].[fGetSystemID] (@physicalMAC varchar(128), @machineKey uniqueidentifier, @motherboardKey varchar(128))
RETURNS int
AS
begin
declare @systemID int;


--  20130313. Fix after analyse activation statistics
--  -------------------------------------------------
--  licenseCount	machineKey	                            motherboardKey	    physicalMac	        isAutogeneratedMachineKey
--  609	            EC7A2334-302B-11DA-8282-F15C26E1F041			                                0
--  118	            03000200-0400-0500-0006-000700080009		                8C:89:A5:69:C7:D2	0
--  115	            F7950E60-FE8D-11D5-BE51-001D60A0BC4D	MB-1234567890		                    0
--  93	            8A5DCE28-0000-8000-385D-FF0010004746	BSN12345678901234567		            0
--  77	            8ED57E06-349E-4F07-9F27-82D860E56BF7	0		                                1
--  59	            348915E0-1DDA-11B2-8000-F24E8F046875	123490EN400015		                    0
--  58	            2224A680-76BB-11E1-8ADD-F0BF9704D21B	N/A		                                0
--  40	            03000200-0400-0500-0006-000700080009	00000000            00:13:8F:65:F8:13   0
--  34	            8B496B40-7A9C-11DA-921B-001731DF2FF7	123456789000		                    0
--  33	            3137E200-CB12-11DF-AB2E-87A29E049CFD	NONE		                            0
--  32	            DB648DFC-1218-DF11-B366-705AB679CEF3	0123456789AB		                    0

--  20130313: validate sting params passed from C++ code in case with empty string
set @physicalMAC    = nullif (@physicalMAC, '');
set @motherboardKey = nullif (@motherboardKey, '');
--  // 20130313: validate sting params passed from C++ code in case with empty string



-- 1) by all three params
	set @systemID = (select top 1 ID 
		from clients.[system]
		where (physicalMAC = @physicalMAC) and (machineKey = @machineKey) and (motherboardKey = @motherboardKey)
		order by id
		)

-- 2) by physicalMAC and machineKey
	if @systemID is null
		set @systemID = (select top 1 ID
		    from clients.[system]
		    where (physicalMAC = @physicalMAC) and (machineKey = @machineKey)
		    order by id
		    )

-- 3) by machineKey only
	if @systemID is null
		set @systemID = (select top 1 ID 
			from clients.system 
			where (machineKey = @machineKey)
			order by id
            )

--  before 20130313
/*
-- 1) all three params
	set @systemID = (select top 1 ID 
		from clients.system 
		where physicalMAC = @physicalMAC and machineKey = @machineKey and isnull(motherboardKey,'') = isnull(@motherboardKey,'')
		order by id
		)

-- 2) by physicalMAC and motherboardKey
	if @systemID is null
		set @systemID = (select top 1 ID 
		from clients.system 
		where (physicalMAC = @physicalMAC and isnull(motherboardKey,'') = isnull(@motherboardKey,''))
		order by id
		) 
-- 3) by machineKey and motherboardKey	
	if @systemID is null
		set @systemID = (select top 1 ID 
			from clients.system 
			where (machineKey = @machineKey and isnull(motherboardKey,'') = isnull(@motherboardKey,''))
			order by id
		)
*/
	
return @systemID;
end


/*
TEST ZONE

select top 10 * from clients.system;
select top 10 * from clients.system where id = 31;

--physicalMAC = @physicalMAC and machineKey = @machineKey and motherboardKey = @motherboardKey
	select  clients.fGetSystemID('F4:6D:04:48:30:13', '4D498CE0-846D-11E0-993F-F46D04483013', '110008970002956')

--physicalMAC = @physicalMAC and machineKey = @machineKey
	select  clients.fGetSystemID('F4:6D:04:48:30:13', '4D498CE0-846D-11E0-993F-F46D04483013', '00')

--physicalMAC = @physicalMAC and motherboardKey = @motherboardKey
	select  clients.fGetSystemID('F4:6D:04:48:30:13', '00000000-0000-0000-0000-000000000000', '110008970002956')

--machineKey = @machineKey and motherboardKey = @motherboardKey
	select  clients.fGetSystemID('00', '4D498CE0-846D-11E0-993F-F46D04483013', '110008970002956')

--machineKey = @machineKey
	select  clients.fGetSystemID('', '4D498CE0-846D-11E0-993F-F46D04483013', '')

--motherboardKey = @motherboardKey
	select  clients.fGetSystemID(null, null, '110008970002956')

--physicalMAC = @physicalMAC	
	select  clients.fGetSystemID('54:04:A6:57:4F:2C', '20214D60-5BCB-11D9-8E10-5404A6574F2C', 'MT7019002213701')
	select  clients.fGetSystemID(null, '20214D60-5BCB-11D9-8E10-5404A6574F2C', null)	
	

    20214D60-5BCB-11D9-8E10-5404A6574F2C	MT7019002213701	


*/
GO
